# Generated by Django 2.2.5 on 2020-05-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='type_pet',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Hamster', 'Hamster'), ('Pássaro', 'Pássaro'), ('Peixe', 'Peixe')], max_length=20, verbose_name='Tipo de Pet'),
        ),
    ]
