# Generated by Django 2.2.5 on 2020-05-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20200512_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='name_pet',
            field=models.CharField(max_length=56, null=True, verbose_name='Nome do Pet'),
        ),
    ]
