# Generated by Django 2.2.5 on 2020-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=999, verbose_name='Código do Produto')),
                ('name', models.CharField(max_length=256, verbose_name='Nome do Produto')),
                ('price', models.FloatField(default=0, verbose_name='Preço')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('stock_entry', models.IntegerField(default=0, verbose_name='Entrada em Estoque')),
                ('stock_exit', models.IntegerField(default=0, verbose_name='Saída em Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
